title: GAIA Workshop
description: Generative AI for Biomedical Image Analysis - Opportunities, Challenges and Futures @ ICCV 2025
theme: jekyll-theme-cayman
baseurl: "/GIGA"
url: ""

# Social media
twitter_username: 
github_username: 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 